version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bank-account
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/:ro
